module Abstractor
  module Enum
    ABSTRACTION_OTHER_VALUE_TYPE_UNKNOWN = 'unknown'
    ABSTRACTION_OTHER_VALUE_TYPE_NOT_APPLICABLE = 'not applicable'
    ABSTRACTION_OTHER_VALUE_TYPES = [ABSTRACTION_OTHER_VALUE_TYPE_UNKNOWN, ABSTRACTION_OTHER_VALUE_TYPE_NOT_APPLICABLE]

    ABSTRACTION_STATUS_NEEDS_REVIEW = 'needs review'
    ABSTRACTION_STATUS_REVIEWED = 'reviewed'
    ABSTRACTION_STATUSES = [ABSTRACTION_STATUS_NEEDS_REVIEW, ABSTRACTION_STATUS_REVIEWED]
  end
end